name = "Naloga01"
uuid = "fd74a74b-0735-4c62-ba36-458666efff84"
version = "0.1.0"
authors = ["Anze Judez <anze.judez@gmail.com>"]

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
